export const motivationMessages = [
  "🔥 You're on fire!",
  "🚀 Keep going!",
  "🎉 Hooray!",
  "💪 Strong work!",
  "🏆 Champion!",
  "👏 Amazing consistency!",
  "🌟 Super progress!",
  "⚡ Fast learner!",
  "🔥 Unstoppable!",
  "💥 Boom! Completed!",
  "🎯 Target hit!",
  "📈 Leveling up!",
  "😎 Smooth work!",
  "🤯 Mind blowing!",
  "💎 Sharp focus!",
  "🚴 Keep moving!",
  "🧠 Smart thinking!",
  "🎮 Game on!",
  "🔥 Elite mindset!",
  "🎉 You nailed it!",
  "⚡ Momentum building!",
  "🚀 Sky is the limit!",
  "💪 Discipline wins!",
  "📊 Progress unlocked!",
  "🌈 Beautiful streak!",
  "🥇 Winner mindset!",
  "🔥 Legendary move!",
  "💥 Impactful step!",
  "🎯 Accuracy!",
  "🧠 Brain power!",
  "🚀 Next level!",
  "😄 Nice work!",
  "🌟 Brilliant!",
  "💪 Strong push!",
  "🔥 Keep pushing!",
  "🎉 Victory!",
  "⚡ Lightning fast!",
  "🏆 Great job!",
  "📈 Growth!",
  "🚀 Power move!",
  "💎 Focus!",
  "🔥 Crushing it!",
  "👏 Keep shining!",
  "🎯 On point!",
  "💥 Success!",
  "🧠 Genius move!",
  "🚀 Forward!",
  "🔥 Progress!",
  "🎉 Celebrate!",
  "💪 Keep going!"
];

export const getRandomMotivation = () => {
  return motivationMessages[
    Math.floor(Math.random() * motivationMessages.length)
  ];
};